### ISSUE TITLE
Install nvgpu error !

### ISSUE THREAD

**Issue by epicwarhd** [rossumai/nvgpu#31]
I got a error when install nvgpu on windows. I have found a similar problem in gg when it says to install on ubuntu so I try in WSL and it's successful. Can anyone help me to install it in windows ?
![image](https://user-images.githubusercontent.com/75321732/236643897-df8935c5-26b5-48bd-b411-490e2c74acdd.png)

**Comment by bzamecnik** [comment]
Thanks. It seems to crash when reading the `README.md` file in `setup.py`.

```
def read_file(path):
    with open(path, 'r') as f:
        return f.read()
```

On Windows for some reason it tries to interpret the file using the CP1252 encoding instead of UTF-8.

* What is your version of Python?
* Could you try to get the README.md file (eg. download it from the GitHub repo) and try calling the `open()` above with different parameters: eg. `'rt'`? I don't have access to Windows.

**Comment by epicwarhd** [comment]
Thank @bzamecnik for your answer,
